// Sample data seed for testing
// Run this via a utility function or manually insert into Supabase

export const SAMPLE_LISTINGS = [
  {
    id: 'listing-001',
    seller_id: 'user-001',
    title: 'iPhone 14 Pro Max - Excellent Condition',
    description: 'Barely used iPhone 14 Pro Max in space black. Original box, charger, and all accessories included. Zero scratches on screen and body. Purchased 2 months ago.',
    category: 'phone',
    brand: 'Apple',
    model: 'iPhone 14 Pro Max',
    condition: 'excellent',
    price: 109999 * 100, // in paise
    images: [
      'https://via.placeholder.com/400x400?text=iPhone+14+Pro+Max+Front',
      'https://via.placeholder.com/400x400?text=iPhone+14+Pro+Max+Back',
    ],
    city: 'Pune',
    area: 'Baner',
    full_address: 'Flat 5, Shriram Aura, Baner, Pune 411045',
    status: 'active',
    is_featured: true,
    featured_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    views: 45,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-002',
    seller_id: 'user-002',
    title: 'Samsung Galaxy S23 Ultra - Like New',
    description: 'Phantom black S23 Ultra with original box. Bought 3 weeks ago, minimal usage. Screen protector applied from day 1. No marks or scratches.',
    category: 'phone',
    brand: 'Samsung',
    model: 'Galaxy S23 Ultra',
    condition: 'excellent',
    price: 89999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=S23+Ultra+Front',
      'https://via.placeholder.com/400x400?text=S23+Ultra+Back',
    ],
    city: 'Pune',
    area: 'Koregaon Park',
    full_address: 'Sunrise Apartments, Koregaon Park, Pune 411001',
    status: 'active',
    is_featured: false,
    views: 67,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-003',
    seller_id: 'user-003',
    title: 'MacBook Pro 14" M2 - 512GB - Good Condition',
    description: 'Silver MacBook Pro 14-inch with M2 chip. 512GB SSD, 8GB RAM. Some keyboard wear, works perfectly. No cracks or liquid damage. Comes with original charger.',
    category: 'laptop',
    brand: 'Apple',
    model: 'MacBook Pro 14" M2',
    condition: 'good',
    price: 119999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=MacBook+Front',
      'https://via.placeholder.com/400x400?text=MacBook+Back',
    ],
    city: 'Pune',
    area: 'Camp',
    full_address: 'Tech Plaza, Camp, Pune 411001',
    status: 'active',
    is_featured: true,
    featured_until: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    views: 102,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-004',
    seller_id: 'user-001',
    title: 'OnePlus 11 5G - Fresh Unboxing',
    description: 'Just unboxed, unused OnePlus 11 5G. Green color. Original box, charger, and accessories. Bought from official store, warranty valid for 18 months.',
    category: 'phone',
    brand: 'OnePlus',
    model: 'OnePlus 11 5G',
    condition: 'excellent',
    price: 54999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=OnePlus+11+Front',
      'https://via.placeholder.com/400x400?text=OnePlus+11+Back',
    ],
    city: 'Pune',
    area: 'Hinjewadi',
    full_address: 'Phoenix Square, Hinjewadi, Pune 411057',
    status: 'active',
    is_featured: false,
    views: 34,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-005',
    seller_id: 'user-004',
    title: 'Dell XPS 13 - Fair Condition - Negotiable',
    description: 'Dell XPS 13 with Intel i5, 8GB RAM, 256GB SSD. Screen has minor scratches. Battery health at 85%. Fully functional, never been repaired.',
    category: 'laptop',
    brand: 'Dell',
    model: 'XPS 13',
    condition: 'fair',
    price: 45999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=XPS+13+Front',
      'https://via.placeholder.com/400x400?text=XPS+13+Back',
    ],
    city: 'Pune',
    area: 'Wakad',
    full_address: 'Mindspace Tower 3, Wakad, Pune 411057',
    status: 'active',
    is_featured: false,
    views: 56,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-006',
    seller_id: 'user-005',
    title: 'Google Pixel 7 Pro - Excellent',
    description: 'Obsidian Pixel 7 Pro. Excellent condition, purchased 4 months ago. Barely used for photography testing. All original accessories included.',
    category: 'phone',
    brand: 'Google',
    model: 'Pixel 7 Pro',
    condition: 'excellent',
    price: 64999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=Pixel+7+Pro+Front',
      'https://via.placeholder.com/400x400?text=Pixel+7+Pro+Back',
    ],
    city: 'Pune',
    area: 'Viman Nagar',
    full_address: 'Silver Oak, Viman Nagar, Pune 411014',
    status: 'active',
    is_featured: false,
    views: 28,
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-007',
    seller_id: 'user-002',
    title: 'ASUS Vivobook 15 - Good Condition',
    description: 'Silver ASUS Vivobook 15 with AMD Ryzen 5, 8GB RAM, 512GB SSD. Light keyboard wear. Battery health 90%. Windows 11 installed.',
    category: 'laptop',
    brand: 'ASUS',
    model: 'Vivobook 15',
    condition: 'good',
    price: 39999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=VivoBook+Front',
      'https://via.placeholder.com/400x400?text=VivoBook+Back',
    ],
    city: 'Pune',
    area: 'Deccan',
    full_address: 'Saarangan, Deccan, Pune 411004',
    status: 'active',
    is_featured: false,
    views: 41,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-008',
    seller_id: 'user-006',
    title: 'iPhone 13 - Good Condition - No Scratches',
    description: 'Sierra blue iPhone 13, 128GB. Excellent screen, minor back casing wear. Charger and cable included. No water damage.',
    category: 'phone',
    brand: 'Apple',
    model: 'iPhone 13',
    condition: 'good',
    price: 59999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=iPhone+13+Front',
      'https://via.placeholder.com/400x400?text=iPhone+13+Back',
    ],
    city: 'Pune',
    area: 'Shivajinagar',
    full_address: 'Aditya Towers, Shivajinagar, Pune 411005',
    status: 'active',
    is_featured: false,
    views: 53,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-009',
    seller_id: 'user-003',
    title: 'Lenovo ThinkPad X1 Carbon - Business Laptop',
    description: 'Lenovo ThinkPad X1 Carbon Gen 10, Intel i7, 16GB RAM, 512GB SSD. Professional laptop, well maintained. Minor hinges squeak, works perfectly.',
    category: 'laptop',
    brand: 'Lenovo',
    model: 'ThinkPad X1 Carbon',
    condition: 'good',
    price: 74999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=X1+Carbon+Front',
      'https://via.placeholder.com/400x400?text=X1+Carbon+Back',
    ],
    city: 'Pune',
    area: 'Kalyani Nagar',
    full_address: 'Corporate Park, Kalyani Nagar, Pune 411006',
    status: 'active',
    is_featured: false,
    views: 72,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'listing-010',
    seller_id: 'user-007',
    title: 'Xiaomi 12 Pro - Fair - Price Reduced',
    description: 'Xiaomi 12 Pro, gray color. Some body scratches, display pristine. Works flawlessly. Reduced price for quick sale.',
    category: 'phone',
    brand: 'Xiaomi',
    model: '12 Pro',
    condition: 'fair',
    price: 34999 * 100,
    images: [
      'https://via.placeholder.com/400x400?text=Mi+12+Pro+Front',
      'https://via.placeholder.com/400x400?text=Mi+12+Pro+Back',
    ],
    city: 'Pune',
    area: 'Kothrud',
    full_address: 'Harmony Residency, Kothrud, Pune 411038',
    status: 'active',
    is_featured: false,
    views: 38,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_USERS = [
  {
    id: 'user-001',
    name: 'Raj Kumar',
    phone: '+919876543210',
    city: 'Pune',
    upi_id: 'raj.kumar@upi',
    trust_score: 85,
    total_transactions: 8,
    is_verified: true,
    is_power_seller: true,
  },
  {
    id: 'user-002',
    name: 'Priya Sharma',
    phone: '+919876543211',
    city: 'Pune',
    upi_id: 'priya.sharma@upi',
    trust_score: 72,
    total_transactions: 5,
    is_verified: true,
    is_power_seller: false,
  },
  {
    id: 'user-003',
    name: 'Amit Patel',
    phone: '+919876543212',
    city: 'Pune',
    upi_id: 'amit.patel@upi',
    trust_score: 65,
    total_transactions: 3,
    is_verified: false,
    is_power_seller: false,
  },
  {
    id: 'user-004',
    name: 'Sneha Desai',
    phone: '+919876543213',
    city: 'Pune',
    upi_id: 'sneha.desai@upi',
    trust_score: 45,
    total_transactions: 2,
    is_verified: false,
    is_power_seller: false,
  },
  {
    id: 'user-005',
    name: 'Vikram Singh',
    phone: '+919876543214',
    city: 'Pune',
    upi_id: 'vikram.singh@upi',
    trust_score: 78,
    total_transactions: 6,
    is_verified: true,
    is_power_seller: false,
  },
  {
    id: 'user-006',
    name: 'Anjali Verma',
    phone: '+919876543215',
    city: 'Pune',
    upi_id: 'anjali.verma@upi',
    trust_score: 55,
    total_transactions: 2,
    is_verified: false,
    is_power_seller: false,
  },
  {
    id: 'user-007',
    name: 'Arjun Malhotra',
    phone: '+919876543216',
    city: 'Pune',
    upi_id: 'arjun.malhotra@upi',
    trust_score: 38,
    total_transactions: 1,
    is_verified: false,
    is_power_seller: false,
  },
];

// Function to seed data into Supabase
export async function seedSampleData(supabaseClient) {
  try {
    console.log('Seeding users...');
    const { error: usersError } = await supabaseClient
      .from('users')
      .upsert(SAMPLE_USERS);
    if (usersError) throw usersError;

    console.log('Seeding listings...');
    const { error: listingsError } = await supabaseClient
      .from('listings')
      .upsert(SAMPLE_LISTINGS);
    if (listingsError) throw listingsError;

    console.log('✓ Sample data seeded successfully!');
    return { success: true };
  } catch (error) {
    console.error('Error seeding data:', error);
    throw error;
  }
}
